name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
        working-directory: backend/crates/bonfire
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: revolt-bonfire-build-artifacts
        path: |
          target/release/
